export default (a,b)=>{
  return  dataArray.slice(a,b)
}

export const getLength =()=>{

    return dataArray.length
}




 const dataArray =   [
    {
      item: 'Sugar1',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar2',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar3',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar4',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar5',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar6',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar7',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar8',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar9',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar10',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagt11',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss12',
      mass: 100,
      case: 12,
      quantity: '',
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
    {
      item: 'Sugar13',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar14',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar15',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar16',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar17',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar18',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar19',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar20',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagtweyqetet3t3ryerhfhr',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagtweyqetet3t3ryerhfhr',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagtweyqetet3t3ryerhfhr',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagtweyqetet3t3ryerhfhr',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagtweyqetet3t3ryerhfhr',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagtweyqetet3t3ryerhfhr',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagtweyqetet3t3ryerhfhr',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagtweyqetet3t3ryerhfhr',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagtweyqetet3t3ryerhfhr',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 1,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 2,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 3,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 4,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 5,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 6,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 7,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      sellUnitPrize: 100,
      id: 9,
    },
    {
      item: 'BSugar',
      mass: 100,
      case: 12,
      quantity: 1,
      amount: 0,
      id: 8,
      sellUnitPrize: 100,
    },
    {
      item: 'Sugar',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 10,
    },
    {
      item: 'Sugagtweyqetet3t3ryerhfhr',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 100,
      id: 11,
    },
    {
      item: 'Aweetssss',
      mass: 100,
      case: 12,
      quantity: 0,
      amount: 0,
      sellUnitPrize: 9.8,
      id: 12,
    },
  ];