import {StyleSheet} from 'react-native';
import {dimensions} from '@utils';
import {getStatusBarHeight} from 'react-native-iphone-x-helper';

const {width_screen, height_screen} = dimensions;

export default StyleSheet.create({
  headerProfile: {
    backgroundColor: '#FFF',
  },
  coverImage: {
    width: width_screen,
    height: 0.31 * height_screen,
    marginTop: '-0.1%',
  },
  linear: {
    width: width_screen,
    height: 0.31 * height_screen,
    position: 'absolute',
    opacity: 0.4,
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    shadowOffset: {width: 0, height: 4},
  },
  icon: {
    position: 'absolute',
    flexDirection: 'row',
    marginTop: getStatusBarHeight() + 10,
    alignItems: 'center',
    alignSelf: 'flex-end',
    width: 0.22 * width_screen,
    justifyContent: 'space-between',
    height: 50,
    right: 8,
  },
  mask: {
    width: 0.87 * width_screen,
    height: 340,
    backgroundColor: '#FFF',
    alignSelf: 'center',
    marginTop: -0.06 * height_screen,
    borderRadius: 10,
    shadowColor: 'rgba(0, 0, 0, 0.08)',
    shadowOffset: {width: 5, height: 10},
    shadowOpacity: 0.3,
    marginBottom: 32,
  },
  img: {
    width: 104,
    height: 104,
    borderRadius: 100,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    marginTop: -0.06 * height_screen,
    overflow: 'hidden',
    alignSelf: 'center',
    borderWidth: 5,
  },
  userName: {
    fontSize: 16,
    color: '#353B48',
    marginTop: 16,
    marginBottom: 7,
    alignSelf: 'center',
  },
  address: {
    fontSize: 12,
    color: '#7F8FA6',
    alignSelf: 'center',
  },
  inbox: {
    width: 142,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#7F8FA6',
    borderRadius: 100,
  },
  rewards: {
    width: 142,
    height: 40,
    backgroundColor: '#ED3269',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  btn: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
    height: 0.1 * height_screen,
    borderBottomWidth: 1,
    borderBottomColor: '#F7F8FA',
  },
  txtInbox: {
    fontSize: 12,
    color: '#7F8FA6',
  },
  txtRewards: {
    fontSize: 12,
    color: '#FFF',
    left: 10,
  },
  numberMessage: {
    height: 16,
    width: 16,
    borderRadius: 8,
    backgroundColor: '#ED3269',
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    right: 6,
    top: -8,
  },
  txtNumberMessage: {
    fontSize: 12,
    color: '#FFF',
  },
  followStyle: {
    flexDirection: 'row',
    marginLeft: 0,
    fontSize: 14,
    color: '#353B48',
    marginTop: 16,
  },
  followers: {
    marginRight: 40,
    marginLeft: 15,
  },
  txtFollow: {
    fontSize: 12,
    color: '#7F8FA6',
  },
  txtNumberFollow: {
    fontSize: 14,
    color: '#353B48',
    top: 3,
  },
  interested: {
    fontSize: 12,
    color: '#7F8FA6',
    marginLeft: 60,
    marginTop: 16,
  },
  tagStyle: {
    flexDirection: 'row',
    marginLeft: 20,
    marginTop: 8,
  },
  txtInterested: {
    fontSize: 14,
    color: '#353B48',
    marginRight: 8,
  },
  arrDown: {
    alignSelf: 'flex-end',
    marginRight: 24,
    bottom: 24,
    height: 30,
    width: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  googleFacebookLogo: {
    height: 60,
    width: 60,
  },
});
