// - REGISTRATION
export const ON_STORE_REGISTRATION_DATA = 'ON_STORE_REGISTRATION_DATA';
// export const REGISTRATION_START = 'REGISTRATION_START';
// export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
// export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

// - LOGIN
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGOUT = 'ON_LOGOUT';

// // AUTHENTICATION
// export const ON_ADDITIONAL_INFO = 'ON_ADDITIONAL_INFO';
// export const ON_STORE_SETUP = 'ON_STORE_SETUP';
// export const ON_POLICY_SETUP = 'ON_POLICY_SETUP';
// export const ON_COMPLETE_REGISTRATION = 'ON_COMPLETE_REGISTRATION';

// SETTINGS
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
// SYSTEM DATA
export const ON_RESET = 'ON_RESET';
export const UPDATE_BANKING_DETAILS = 'UPDATE_BANKING_DETAILS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const STORE_ORDER = 'STORE_ORDER';
export const RESET_STORE_ORDER = 'RESET_STORE_ORDER';

//STYSTEM REDUCER
export const CREATE_PDF_BATCH_ORDER = 'CREATE_PDF_BATCH_ORDER';
export const ACTIVE_STOCK_TAKING = 'ACTIVE_STOCK_TAKING';
export const SAVE_DELIVERY_STOCK = 'SAVE_DELIVERY_STOCK';
export const INTIALISE_DELIVERY_STOCK = 'INTIALISE_DELIVERY_STOCK';
export const RESET_DELIVERY_STOCK = 'RESET_DELIVERY_STOCK';
export const WRITE_SHOP_STOCK_SAVE = 'WRITE_SHOP_STOCK_SAVE';
export const RESET_WRITE_SHOP_STOCK = 'RESET_WRITE_SHOP_STOCK';
export const ON_SAVE_SHOP_SELL_CART = 'ON_SAVE_SHOP_SELL_CART';
export const ON_RESET_SHOP_SELL_CART = 'ON_RESET_SHOP_SELL_CART';
export const ON_SAVE_CLIENTS_WORKERS_ORDERS = 'ON_SAVE_CLIENTS_WORKERS_ORDERS';
export const RESET_CLIENTS_WORKERS_ORDERS = 'RESET_CLIENTS_WORKERS_ORDERS';
