const ROUTES = {
  /**
   * MAIN SCREENS ENTRANCE FOR STACKS
   */
  ClientStack: 'ClientStack',
  ClientsOrderDetails: 'ClientsOrderDetails',
  AdminStack: 'AdminStack',
  PreviewOrder: 'PreviewOrder',
  ConvertToPdf: 'ConvertToPdf',
  SuccessOrder: 'SuccessOrder',
  POSScanproduct: 'POSScanproduct',
  POSProducts: 'POSProducts',
  POSAmount: 'POSAmount',
  POSScreenTab: 'POSScreenTab',
  POSPaymentOption: 'POSPaymentOption',
  Credits: 'Credits',
  MyOrders: 'MyOrders',
  Invoices: 'Invoices',
  TabProfile: 'TabProfile',
  ProductDetails: 'ProductDetails',
  POSHistoryDetail: 'POSHistoryDetail',
  POSHistory: 'POSHistory',
  CreateOrderDetails: 'CreateOrderDetails',
  ForgetPassword: 'ForgetPassword',
  WriteStock: 'WriteStock',
  LossRecords: 'LossRecords',
  ExpenseRecords: 'ExpenseRecords',
  Previledges: 'Previledges',
  OrderRecords: 'OrderRecords',
  ProfitsProfile: 'ProfitsProfile',
  DebtsList: 'DebtsList',
  Profits2: 'Profits2',
  RecordDeliveredStockTwo: 'RecordDeliveredStockTwo',
  RecordDeliveredStockThree: 'RecordDeliveredStockThree',
  ShopUsers: 'ShopUsers',
  ShopUsersDetail: 'ShopUsersDetail',
  AllUsersList: 'AllUsersList',
  NotFound: 'NotFound',
  UsersOrders: 'UsersOrders',
  AdminLink: 'AdminLink',
  Reports: 'Reports',
  ReportsTabScreenTab: 'ReportsTabScreenTab',
  SelectedShop: 'SelectedShop',
  ReportsLists: 'ReportsLists',
  Products: 'Products',
  ChooseOptionForAccount: 'ChooseOptionForAccount',
  Login: 'Login',
  OrdersTabScreen: 'OrdersTabScreen',
  ScanBarCode: 'ScanBarCode',
  Inbox: 'Inbox',
  CreateOrder2: 'CreateOrder2',
  CreateShop: 'CreateShop',
  CategoryBrandsScreen: 'CategoryBrandsScreen',
  Brands: 'Brands',
  ShopCreatingSuccessfull: 'ShopCreatingSuccessfull',
  BottomTabStack: 'BottomTabStack',
  ExpenseLossesSuccessfullRecorded: 'ExpenseLossesSuccessfullRecorded',
  RecordDeliveredStockSuccess: 'RecordDeliveredStockSuccess',
  StartStockTaking: 'StartStockTaking',
  RegisterAccount: 'RegisterAccount',
  ChooseAccount: 'ChooseAccount',
  ProfitsDetails: 'ProfitsDetails',
  RecordDeliveredDetails: 'RecordDeliveredDetails',
  ExpenseDetails: 'ExpenseDetails',
  LossesDetails: 'LossesDetails',
  SingleCategory: 'SingleCategory',
  CreateOrder3: 'CreateOrder3',
  DeliveriesReportList: 'DeliveriesReportList',
  DeliveriesReportDetail: 'DeliveriesReportDetail',
  ShopStockList: 'ShopStockList',
  StockTakingList: 'StockTakingList',
  TransactionsList: 'TransactionsList',
  AdminShopList: 'AdminShopList',
  /**
   * AUTH ROUTE SCREENS 
   */
  Loading: 'Loading',
  Walkthrough: 'Walkthrough',
  CompleteRegistration: 'CompleteRegistration',
  SuccessRegistration: 'SuccessRegistration',
  AccountExist: 'AccountExist',
  Tour: 'Tour',
  AdditionalInfor: 'AdditionalInfor',
  StoreSetup: 'StoreSetup',
  PolicySetup: 'PolicySetup',
  ForthScreen: 'ForthScreen',
  Profits: 'Profits',
  StockTaking: 'StockTaking',
  RecordDeliveredStock: 'RecordDeliveredStock',
  SupportTeamInbox: 'SupportTeamInbox',
  SelectUsersForBroadcast: 'SelectUsersForBroadcast',
  SelectShopSettings: 'SelectShopSettings',
  /**
   * ADMIN SCREENS TO BE RENDERED
   */
  Home: 'Home',
  AdminProfile: 'AdminProfile',
  Shops: 'Shops',
  Search: 'Search',
  Drawer: 'Drawer',
  Orders: 'Orders',
  Messages: 'Messages',
  MessagesList: 'MessagesList',
  BroadCastMessaging: 'BroadCastMessaging',
  Profile: 'Profile',
  HomeStack: 'HomeStack',
  ProfileTopTab: 'ProfileTopTab',
  Settings: 'Settings',
  ProfileScreen: 'ProfileScreen',
  Tarven: 'Tarven',
  Grocery: 'Grocery',
  WholesaleList: 'WholesaleList',
  AddWholeSale: 'AddWholeSale',
  AddProducts: 'AddProducts',
  ScanProducts: 'ScanProducts',
  GetBarCode: 'GetBarCode',
  EditProduct: 'EditProduct',
  SearchScreen: 'SearchScreen',
  HomeScreen: 'HomeScreen',
  ShopsScreen: 'ShopsScreen',
  DrawerStack: 'DrawerStack',
  Expenses: 'Expenses',
  UsersList: 'UsersList',
  StoreManager: 'StoreManager',
  OrderDetails: 'OrderDetails',
  BatchOrderDetails: 'BatchOrderDetails',
  EditBatchOrder: 'EditBatchOrder',
  ConvertBatchToPDF: 'ConvertBatchToPDF',
  Categories: 'Categories',
  EditSettings: 'EditSettings',
  SelectFontOption: 'SelectFontOption',
  SelectDarkOption: 'SelectDarkOption',
  ThemeScreen: 'ThemeScreen',
  AboutUs: 'AboutUs',
  FeedBack: 'FeedBack',
  Updates: 'Updates',
  /**
  * CLIENT SCREENS TO BE RENDERED
  */
  ClientHome: 'ClientHome',
  Notifications: 'Notifications',
  SearchApp: 'SearchApp',
  CreateOrder: 'CreateOrder',
};

export default ROUTES;
