import {StyleSheet} from 'react-native';
import {dimensions, FONTS, Colors} from '@utils';
import {getBottomSpace} from 'react-native-iphone-x-helper';

const {width_screen, height_screen} = dimensions;
export default StyleSheet.create({
  container: {
    flex: 1,
    height: height_screen + 100,
  },
  lottie: {},
  topText: {fontSize: 25},

  contentContainerStyle: {
    width: width_screen * 3,
    height: height_screen + 500,
  },
  note: {
    fontSize: 14,
    fontFamily: FONTS.Regular,
    color: Colors.WHITE,
    position: 'absolute',
    bottom: height_screen * 0.25,
    alignSelf: 'center',
  },
  userType: {
    fontSize: 25,
    fontFamily: FONTS.Regular,
    color: Colors.BLACK,
    letterSpacing: 7,
  },
  cross: {
    fontSize: 14,
    fontFamily: FONTS.Regular,
    color: Colors.WHITE,
    position: 'absolute',
    bottom: height_screen * 0.2,
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,1)',
    height: 30,
    width: 30,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0.4,
  },
  crossText: {
    color: Colors.BLACK,
    fontWeight: 'bold',
  },

  bottom: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    paddingBottom: getBottomSpace() + 90,
    paddingHorizontal: width_screen * 0.064,
  },
  registerLogin: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    paddingBottom: getBottomSpace() + 90,
    paddingHorizontal: width_screen * 0.064,
  },
  fbtwitter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  regloginContainer: {
    flexDirection: 'row',
  },
  accountSelect: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    paddingBottom: getBottomSpace() + 60,
    paddingHorizontal: width_screen * 0.064,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  btnFb: {
    width: width_screen * 0.41,
    height: 50,
    backgroundColor: '#3B5998',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  google: {
    width: width_screen * 0.41,
    height: 50,
    backgroundColor: Colors.WHITE,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  admin: {
    width: width_screen * 0.5,
    height: 50,
    backgroundColor: 'rgba(255,255,255,1)',
    borderRadius: 30,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    borderColor: 'blue',
  },
  user: {
    width: width_screen * 0.5,
    height: 50,
    backgroundColor: 'rgba(255,255,255,1)',
    borderRadius: 30,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 10,
    borderWidth: 0.9,
    borderColor: Colors.WHITE,
  },
  selectText: {
    fontSize: 15,
    letterSpacing: 7,
    fontWeight: '600',
  },
  btnTwitter: {
    width: width_screen * 0.41,
    height: 50,
    backgroundColor: '#1DA1F2',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  googleLogo: {
    height: 50,
    width: 50,
  },
  registerLoginbtn: {
    width: width_screen * 0.4,
    height: 50,
    backgroundColor: 'rgba(255,255,255,1)',
    borderRadius: 30,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    borderColor: 'blue',
  },
  lottie: {
    height: 450,
    width: 450,
  },
  email: {
    // backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 50,
  },
});
